# This is the docker-compose script for local development.
# For the latest version of the docker images see:
# https://github.com/Azure/pcs-cli/blob/master/remotemonitoring/single-vm/docker-compose.dotnet.yml
#
# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - note how this file references many environment variables, either set
#   them in the .env file or edit this file adding the values here
# - run `docker-compose up`
# - open the browser at http://127.0.0.1:10443
#
# For more information see
# https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet

version: "3"

services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:testing
    ports:
      - "8080:10080"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    volumes:
    # Required volume for app certs
      - ./config/nginx.conf:/app/config/nginx.conf:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:testing
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
      - diagnostics
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
  # NOTE: Volumes disabled for local development, uncomment if enabling auth
  # volumes:
  #   - ./webui-config.js:/app/build/webui-config.js:ro

  auth:
    image: azureiotpcs/pcs-auth-dotnet:testing
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  iothubmanager:
    image: azureiotpcs/iothub-manager-java:testing
    depends_on:
      - auth
      - storageadapter
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:DS-1.0.2
    depends_on:
      - storageadapter
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
  # How one could mount custom device models
  # NOTE: Volumes disabled for local development
  # volumes:
  #   - ./my-device-models:/app/data:ro

  telemetry:
    image: azureiotpcs/telemetry-java:testing
    depends_on:
      - auth
      - storageadapter
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  config:
    image: azureiotpcs/pcs-config-java:testing
    depends_on:
      - auth
      - storageadapter
      - devicesimulation
      - telemetry
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-java:testing
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  asamanager:
    image: azureiotpcs/asa-manager-dotnet:testing
    depends_on:
      - telemetry
      - iothubmanager
      - config
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  diagnostics:
    image: azureiotpcs/pcs-diagnostics-dotnet:testing
    depends_on:
      - config
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET