# You can use this file to setup the service locally, and start all the
# containers at once.
#
# Usage:
# - setup all the environment variables referenced below
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  config:
    image: azureiotpcs/pcs-config-java:testing
    depends_on:
      - storageadapter
      - telemetry
      - devicesimulation
      - iothubmanager
    ports:
      - "9005:9005"
    environment:
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_DEVICESIMULATION_WEBSERVICE_URL=http://devicesimlation:9003/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_BINGMAP_KEY

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-java:testing
    ports:
      - "9022:9022"
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      
  telemetry:
    image: azureiotpcs/telemetry-java:testing
    ports:
      - "9004:9004"
    environment:
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022:/v1
      
  devicesimulation:
    image: azureiotpcs/pcs-device-simulation-java:testing
    ports:
      - "9003:9003"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022:/v1
      
  iothubmanager:
    image: azureiotpcs/iothub-manager-java:testing
    ports:
      - "9002:9002"
    environment:
      - PCS_IOTHUB_CONNSTRING
